CREATE TABLE IF NOT EXISTS public.members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(100),
    membership_type VARCHAR(20) NOT NULL DEFAULT 'FREE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT members_membership_type_check CHECK (membership_type IN ('FREE', 'PREMIUM'))
);

CREATE TABLE IF NOT EXISTS public.membership_plans (
    plan_code VARCHAR(20) PRIMARY KEY,
    plan_name VARCHAR(100) NOT NULL,
    monthly_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    news_limit INTEGER,
    etf_holding_limit INTEGER,
    max_backtest_years INTEGER,
    allow_backtest BOOLEAN NOT NULL DEFAULT false,
    show_ai_report BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.watchlist (
    watchlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES public.members(member_id) ON DELETE CASCADE,
    symbol VARCHAR(40) NOT NULL,
    asset_type VARCHAR(30) NOT NULL,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT watchlist_asset_type_check CHECK (asset_type IN ('STOCK', 'ETF', 'CRYPTO', 'XSTOCK', 'COMMODITY', 'REIT', 'BOND')),
    CONSTRAINT watchlist_member_symbol_asset_unique UNIQUE (member_id, symbol, asset_type)
);

CREATE TABLE IF NOT EXISTS public.saved_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES public.members(member_id) ON DELETE CASCADE,
    report_type VARCHAR(40) NOT NULL,
    title VARCHAR(255) NOT NULL,
    symbol VARCHAR(40),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT saved_reports_report_type_check CHECK (report_type IN ('STOCK', 'ETF', 'EARNINGS', 'BACKTEST', 'MARKET', 'SHADOW', 'LEARNING', 'AI'))
);

CREATE INDEX IF NOT EXISTS idx_watchlist_member_id ON public.watchlist(member_id);
CREATE INDEX IF NOT EXISTS idx_saved_reports_member_id ON public.saved_reports(member_id);
CREATE INDEX IF NOT EXISTS idx_saved_reports_report_type ON public.saved_reports(report_type);

INSERT INTO public.membership_plans (plan_code, plan_name, monthly_price, news_limit, etf_holding_limit, max_backtest_years, allow_backtest, show_ai_report)
VALUES
    ('FREE', 'Free Plan', 0, 3, 5, 0, false, false),
    ('PREMIUM', 'Premium Plan', 19.99, NULL, NULL, 3, true, true)
ON CONFLICT (plan_code) DO UPDATE SET
    plan_name = EXCLUDED.plan_name,
    monthly_price = EXCLUDED.monthly_price,
    news_limit = EXCLUDED.news_limit,
    etf_holding_limit = EXCLUDED.etf_holding_limit,
    max_backtest_years = EXCLUDED.max_backtest_years,
    allow_backtest = EXCLUDED.allow_backtest,
    show_ai_report = EXCLUDED.show_ai_report;

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_reports ENABLE ROW LEVEL SECURITY;

