# 서버 포트 설정
server.port=8083

# JSP 설정 (prefix, suffix)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MyBatis 설정 (자바 패키지 내부의 XML을 찾도록 수정)
mybatis.mapper-locations=classpath:com/joe/chickenv/mapper/**/*.xml
mybatis.type-aliases-package=com.joe.chickenv.model

# Database 설정 (H2 메모리 DB 우선 사용)
spring.datasource.url=jdbc:h2:mem:chickenvdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# 로그 설정
logging.level.com.joe.chickenv=debug
