spring.application.name=kosmo_project-solo

#----- 포트번호 (충돌방지)

server.port=18083


#------ jsp 경로 앞/뒤 지정

spring.mvc.view.prefix=/WEB-INF/views/

spring.mvc.view.suffix=.jsp
#-----//prefix : 접두사 suffix : 접미사 

#------연결 정보

# username

spring.datasource.hikari.username=postgres.ijkgxsmwkymoqndvzbrq

# password

spring.datasource.hikari.password=kcPAsHOqhSfgPZjP

# url

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres

# driver

spring.datasource.driver-class-name=org.postgresql.Driver


#-------mybatis

#카멜 케이스로 변환

mybatis.configuration.map-underscore-to-camel-case=true

#---config의 typealias 대체 / 같은 class명이 존재 하면 에러 발생

mybatis.type-aliases-package=com.joe.app


# Test 또는 대량을 INSERT시 CASH충돌 해결

spring.datasource.hikari.data-source-properties.prepareThreshold=0


#-- file 관리

#--multipart 사용 여부

spring.servlet.multipart.enabled=true

#-- 파일 하나당 최대 크기 설정 제한

spring.servlet.multipart.max-file-size=10MB

#-- 총 파일의 최대 크기 설정 제한

spring.servlet.multipart.max-request-size=100MB


#-- 파일 저장 관리

app.upload.base=C:\\upload\\


app.upload.path=file:\\C:\\upload\\


app.member=C:\\upload\\member\\

#---
app.board.notice=notice

app.board.qna=qna

app.product=product


#--- 파일 위치를 연결할 가상의 URL

app.upload.url=files/**
