CREATE TABLE IF NOT EXISTS public.stock_prices (
    price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(40) NOT NULL,
    trade_date DATE NOT NULL,
    open_price NUMERIC(20, 6),
    high_price NUMERIC(20, 6),
    low_price NUMERIC(20, 6),
    close_price NUMERIC(20, 6),
    adjusted_close NUMERIC(20, 6),
    volume BIGINT,
    source_name VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT stock_prices_symbol_date_unique UNIQUE (symbol, trade_date)
);

CREATE TABLE IF NOT EXISTS public.etf_profiles (
    etf_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(40) NOT NULL UNIQUE,
    etf_name VARCHAR(255),
    issuer VARCHAR(160),
    expense_ratio NUMERIC(10, 6),
    aum NUMERIC(24, 2),
    inception_date DATE,
    source_name VARCHAR(80),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.etf_holdings (
    holding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etf_symbol VARCHAR(40) NOT NULL,
    holding_symbol VARCHAR(40) NOT NULL,
    holding_name VARCHAR(255),
    weight_percent NUMERIC(10, 6),
    as_of_date DATE,
    source_name VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT etf_holdings_symbol_unique UNIQUE (etf_symbol, holding_symbol, as_of_date)
);

CREATE TABLE IF NOT EXISTS public.news_cache (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(80),
    title VARCHAR(500) NOT NULL,
    summary TEXT,
    url TEXT NOT NULL,
    category VARCHAR(80),
    related_symbols TEXT,
    sentiment_score NUMERIC(10, 6),
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT news_cache_url_unique UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS public.earnings_results (
    earnings_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(40) NOT NULL,
    fiscal_period VARCHAR(40),
    report_date DATE,
    expected_eps NUMERIC(20, 6),
    actual_eps NUMERIC(20, 6),
    eps_surprise NUMERIC(20, 6),
    expected_revenue NUMERIC(24, 2),
    actual_revenue NUMERIC(24, 2),
    revenue_surprise NUMERIC(24, 2),
    source_name VARCHAR(80),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT earnings_symbol_period_unique UNIQUE (symbol, fiscal_period, report_date)
);

CREATE TABLE IF NOT EXISTS public.backtest_results (
    backtest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_ref VARCHAR(120),
    symbol VARCHAR(40) NOT NULL,
    strategy_name VARCHAR(120) NOT NULL,
    period_years INTEGER NOT NULL,
    initial_cash NUMERIC(20, 2) NOT NULL,
    final_value NUMERIC(20, 2),
    return_rate NUMERIC(12, 6),
    win_rate NUMERIC(12, 6),
    max_drawdown NUMERIC(12, 6),
    trade_count INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.market_indicators (
    indicator_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_code VARCHAR(80) NOT NULL,
    indicator_name VARCHAR(255) NOT NULL,
    country_code VARCHAR(10),
    asset_class VARCHAR(40),
    observed_date DATE NOT NULL,
    indicator_value NUMERIC(24, 8),
    unit VARCHAR(80),
    source_name VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT market_indicators_unique UNIQUE (indicator_code, observed_date)
);

CREATE INDEX IF NOT EXISTS idx_stock_prices_symbol_date ON public.stock_prices(symbol, trade_date DESC);
CREATE INDEX IF NOT EXISTS idx_etf_holdings_etf_symbol ON public.etf_holdings(etf_symbol);
CREATE INDEX IF NOT EXISTS idx_news_cache_category_published ON public.news_cache(category, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_earnings_results_symbol_date ON public.earnings_results(symbol, report_date DESC);
CREATE INDEX IF NOT EXISTS idx_market_indicators_code_date ON public.market_indicators(indicator_code, observed_date DESC);

