spring.application.name=kosmo_joe_fin

server.port=8081
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.sql.init.encoding=UTF-8

mybatis.configuration.map-underscore-to-camel-case=true 
mybatis.type-aliases-package=com.joe.fin


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.alphavantage.api.key=${ALPHAVANTAGE_API_KEY:}

clinicaltrials.base.url=https://clinicaltrials.gov/api/v2
#
openfda.api.key=${OPENFDA_API_KEY:}
openfda.base.url=https://api.fda.gov
#
ncbi.api-key=${NCBI_API_KEY:}
ncbi.base-url=https://eutils.ncbi.nlm.nih.gov/entrez/eutils

# 현재 무료 버전 (글로벌 제재 대상자, 범죄 연루 정치인 통합 검색) 기한 11/06/26 50req/mo usage : view
opensanctions.api-key=${OPENSANCTIONS_API_KEY:}
opensanctions.base-url=https://api.opensanctions.org

#국가 법령 정보 센터
law.api-key=${LAW_API_KEY:}
law.base-url=https://www.law.go.kr/DRF/lawService.do

