drop table if exists watchlist;
drop table if exists members;

create table members (
    member_id integer generated by default as identity primary key,
    email varchar(255) not null unique,
    display_name varchar(100) not null,
    membership_type varchar(20) not null,
    password_hash varchar(255) not null default 'demo',
    created_at timestamp not null default current_timestamp
);

create table watchlist (
    watchlist_id integer generated by default as identity primary key,
    member_id integer not null,
    symbol varchar(40) not null,
    asset_type varchar(30) not null,
    memo varchar(1000),
    created_at timestamp not null default current_timestamp
);
